#!/usr/bin/env bash

# Script that configures Nginx server with a custom header

apt-get -y update
apt-get -y install nginx

echo "Hello world" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Add custom header configuration to Nginx
sed -i '/server_name _;/a \\tadd_header X-Served-By "$HOSTNAME";' /etc/nginx/sites-available/default

# Start Nginx service
service nginx start
