#!/usr/bin/env bash
#Script that replace values in /etc/hosts file
sudo cp /etc/hosts ~/new.hostfile
sed -i 's/127.0.0.1/127.0.0.2/' ~/new.hostfile
sed -i "3i8.8.8.8	facebook.com" ~/new.hostfile
cp -f ~/new.hostfile /etc/hosts
